# Backend services configuration
services:
    - name: api
      host: localhost
      port: 3000
      health_check:
          path: /health
          retry_count: 10
          retry_delay_seconds: 1

    - name: webapp
      host: localhost
      port: 8080
      health_check:
          path: /
          retry_count: 5
          retry_delay_seconds: 2

# Routing configuration with multiple types
routes:
    # Proxy to backend service
    - domain: api.example.com
      type: service
      service: api

    # Static file serving
    - domain: static.example.com
      type: static
      root: /var/www/static
      index:
          - index.html
          - index.htm
      try_files:
          - $uri
          - $uri/
          - /404.html

    # Another static site with SPA support
    - domain: app.example.com
      type: static
      root: /var/www/app
      try_files:
          - $uri
          - /index.html # SPA fallback

    # Default catch-all route
    - domain: "*"
      type: service
      service: webapp

# API and proxy ports
api_port: 1143
proxy_port: 1144
