#!/bin/bash
### BEGIN INIT INFO
# Provides:          traffic-switcher
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Traffic Switcher HTTP Reverse Proxy
# Description:       HTTP reverse proxy with dynamic port switching
### END INIT INFO

NAME=traffic-switcher
DAEMON=/usr/local/bin/tsctl
PIDFILE=/var/run/$NAME.pid
LOGFILE=/var/log/$NAME.log
CONFIG=/etc/traffic-switcher/config.yaml
USER=traffic-switcher

# Source function library
. /etc/rc.d/init.d/functions 2>/dev/null || true

start() {
    echo -n "Starting $NAME: "
    
    if [ -f $PIDFILE ] && kill -0 $(cat $PIDFILE) 2>/dev/null; then
        echo "already running"
        return 1
    fi
    
    su - $USER -c "$DAEMON start --daemon --pid-file $PIDFILE --log-file $LOGFILE --config $CONFIG"
    
    if [ $? -eq 0 ]; then
        echo "OK"
    else
        echo "FAILED"
        return 1
    fi
}

stop() {
    echo -n "Stopping $NAME: "
    
    if [ ! -f $PIDFILE ]; then
        echo "not running"
        return 1
    fi
    
    $DAEMON stop --pid-file $PIDFILE
    
    if [ $? -eq 0 ]; then
        rm -f $PIDFILE
        echo "OK"
    else
        echo "FAILED"
        return 1
    fi
}

status() {
    $DAEMON status --pid-file $PIDFILE
}

restart() {
    stop
    sleep 2
    start
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status
        ;;
    restart|reload)
        restart
        ;;
    *)
        echo "Usage: $0 {start|stop|status|restart|reload}"
        exit 1
        ;;
esac

exit 0